### ISSUE TITLE
event log functionality for machines

### ISSUE THREAD

**Issue by gemagomez** [Linaro/mr-provisioner#17]
Machines should have an event log that keeps a list of relevant events for some fixed amount of time (e.g. 30 days).

The event log should include things like:

 - machine assigned/unassigned
 - rebooted
 - console accessed
 - high-level DHCP packet trace (needs Kea integration)
 - preseed accessed
 - phoned-home (needs phone home logic, will be tracked in a separate issue)

This should be implemented as a separate table where each row represent a log entry for the machine, and has a JSONB column containing event payload (i.e. not storing fixed strings of events).

**Comment by bwalex** [comment]
Also include any template substitution errors that happen during preseed access.
