### ISSUE TITLE
sort usernames

### ISSUE THREAD

**Issue by hrw** [Linaro/mr-provisioner#2]
When machine needs to be assigned to someone admin can select such person from a list. 

But list is unsorted ;(

There is search box there but that requires extra mouse clicks.

**Comment by gemagomez** [comment]
The new ui will be more usable. 
However, in essence when assigning someone you should type the first name of their letter and they appear. It is a search box, not supposed to be navigated up and down searching for people. The other option is to remove all the names and let the user type the assignee they want.
