### ISSUE TITLE
Add new files category and handle FTP as well

### ISSUE THREAD

**Issue by LGraemeG** [Linaro/mr-provisioner#24]
Some usecases such as firmware upgrade need access to FTP server. As most FTP servers are quite archaic it might make sense to set one up to share the same file directory as TFTP.

Add a new Misc/FTP category to the Images handling on the app so you can upload non kernel non initrd images. Because the directory is shared these would be available both by tftp and by ftp.

D0X machines use FTP for firmware upgrade, ThunderX machines use tftp for firmware upgrade so this would work for both types of machine without leaving the app environment.

It is a usecase for Server Architecture/QA teams to replace/test firmwares as ERP firmware is one of our deliverables.

**Comment by gemagomez** [comment]
FTP is out of the scope of this project.
