### ISSUE TITLE
Deleting images

### ISSUE THREAD

**Issue by gemagomez** [Linaro/mr-provisioner#25]
Deleting an image currently deletes the association with any machine that is using it. This is dangerous as some users may be relying on that kernel/initrd being there for their testing.
I think a better approach will be to:
- ensure the user deleting the image is the only one using it, then automatically remove it from all his assigned machines and any free machines that may have it
- if there are other assigned machines with this image, tell the user trying to delete that he cannot because there are others using it, and give a list of the other users names on the error

This fix needs some more thinking, but essentially we should play it safe and not allow deletion of test artifacts that others are relying on.

**Comment by danrue** [comment]
As a user, I don't expect to be able to delete something that is being used, or having it automatically removed from my machines.

Something like this I think is most simple: "Error: Cannot delete. Image in use". If you want to be really nice, list the machines that are using the image in the error.

**Comment by gemagomez** [comment]
This issue is solved by the new UI. Images can only be deleted if they are not associated to a machine.
