### ISSUE TITLE
Add machine properties

### ISSUE THREAD

**Issue by hrw** [Linaro/mr-provisioner#3]
Would be nice to have some machine properties available:

- model name
- cpu (name, sockets, cores, threads)
- memory
- storage (type and size)

**Comment by hrw** [comment]
One way of doing it is map of machines<>properties. It requires three database tables:

1. machines
2. properties
3. machine_properties

Machines table exists already and we need just ID from there.

Properties table:

ID | name | order
-|-|-
1|CPU cores|10
2|CPU name|02
3|CPU sockets|05
4|Memory size|30
5|Storage SSD|40
6|Storage HDD|50
7|Model name|01

Then table with mapping (machine_properties):

ID|machine_id|property_id|value
-|-|-|-
1|1|1|8
2|1|2|X-Gene 1
3|1|4|64GB
4|1|5|480GB
5|2|3|4
6|2|1|64
7|2|2|MemberX confidential CPU name
8|2|4|128GB
9|2|5|512GB
10|2|6|2TB
11|2|6|2TB
12|1|7|Moonshot m400
13|2|7|RT249WX9

This tells us that Machine ID 1 is m400 cartridge with X-Gene 1 cpu with 8 cores, has 64GB ram and 480GB SSD. Machine  ID 2 is RT249WX9, has  "MemberX confidential CPU name" with 4 sockets and 64 cores in total + 128GB ram, 512GB SSD and two 2TB hard drives.

**Comment by gemagomez** [comment]
Superseded by #5
