### ISSUE TITLE
Machines list shows wrong IP address

### ISSUE THREAD

**Issue by hrw** [Linaro/mr-provisioner#35]
r1-m1-c01n1 has IPv4 address configured to fixed value. But list of machines shows wrong one:

![image](https://user-images.githubusercontent.com/185508/28266239-15f93fc8-6af4-11e7-9dda-5198e044b0c0.png)

It should be 10.101.96.5 one:

![image](https://user-images.githubusercontent.com/185508/28266276-3a8c69a0-6af4-11e7-8c4c-f4a95a0d1fd8.png)

**Comment by bwalex** [comment]
The lease IP shows, as the name says, a lease IP. If you have configured the machine with a static IP, that implies that you'd use that static IP during installation/preseed/etc. However, the machine will still get a *leased* IP during early BOOTP/DHCP/etc, and that's the one that will appear there. The "Last seen" field is there to let you know when that lease was acquired.
