### ISSUE TITLE
Make machine views title the name of the machine

### ISSUE THREAD

**Issue by gemagomez** [Linaro/mr-provisioner#38]
Currently when a few tabs are open is difficult to see which belongs to what machine. Change the app so machine views show the name of the machine on the tab, rather than the name of the lab.

**Comment by hrw** [comment]
See #40

**Comment by bwalex** [comment]
I'd suggest you use something like react-document-title within the affected components; that should make it reasonably trivial to show the machine name (or anything else really) in the title.
