### ISSUE TITLE
Change layout of preseed edit page

### ISSUE THREAD

**Issue by hrw** [Linaro/mr-provisioner#39]
When user edits preseed file there is help displayed about edit field:

![image](https://user-images.githubusercontent.com/185508/28523491-05d93e7a-707d-11e7-8072-6a34742b5104.png)

But if we move templates hints to the right we may put a bit bigger editor in same area:

![image](https://user-images.githubusercontent.com/185508/28524103-76021986-707f-11e7-9040-030a1e11c08e.png)

**Comment by bwalex** [comment]
That would break the responsive design and actually break usability. The height of the text area could be changed without any change to the layout, if so desired. That said, you might want to consider an external editor to start with and just paste things in. For quick fixes, the current height seems sufficient.
