### ISSUE TITLE
Expose machine name as netcfg/hostname for PXE boot

### ISSUE THREAD

**Issue by hrw** [Linaro/mr-provisioner#41]
We mostly use Debian installer for PXE boot. There are already few options hardcoded for it to make it work fine. 

Except hostname. Adding "netcfg/hostname=MACHINENAME" makes d-i use it as hostname for DHCP query and for resulting system.

**Comment by bwalex** [comment]
You can already achieve it by using the (documented) `{{ hostname }}` interpolation in the preseed.
