### ISSUE TITLE
Download-log page loses line breaks

### ISSUE THREAD

**Issue by chase-qi** [Linaro/mr-provisioner#67]
Click 'Download log' button, the page rendered shown as:
`tcgetattr: Inappropriate ioctl for device [SOL Session operational. Use ~? for help] Debian GNU/Linux 9 debian ttyAMA0 debian login: root Password: Last login: Wed Jan 17 10:08:30 GMT 2018 on ttyAMA0 Linux debian 4.14.0-254-arm64 #1 SMP Debian 4.14.0.linaro.254-1 (2017-12-04) aarch64 The programs included with the Debian GNU/Linux system are free software; the exact distribution terms for each program are described in the individual files in /usr/share/doc/*/copyright. Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law. root@debian:~# ls /etc/ adduser.conf	init	python adjtime	init.d	python2.7 alternatives	initramfs-tools python3 apm	inputrc	python3.5 apparmor	iproute2	rc0.d apparmor.d	issue	rc1.d apt	issue.net	rc2.d bash.bashrc	kernel	rc3.d bash_completion	kernel-img.conf rc4.d bash_completion.d	ldap	rc5.d bindresvport.blacklist	ld.so.cache	rc6.d binfmt.d	ld.so.conf	rcS.d ca-certificates	ld.so.conf.d	reportbug.conf ca-certificates.conf	libaudit.conf	resolv.conf calendar	locale.alias	rmt console-setup	locale.gen	rpc cron.d	localtime	rsyslog.conf cron.daily	logcheck	rsyslog.d cron.hourly	login.defs	securetty cron.monthly	logrotate.conf	security crontab	logrotate.d	selinux cron.weekly	machine-id	services dbus-1	magic	sgml debconf.conf	magic.mime	shadow debian_version	mailcap	shadow- default	mailcap.order	shells deluser.conf	manpath.config	skel dhcp mime.types	ssh dictionaries-common	mke2fs.conf	ssl discover.conf.d	modprobe.d	staff-group-for-usr-local discover-modprobe.conf	modules	subgid dpkg	modules-load.d	subgid- emacs	motd	subuid environment	mtab	subuid- fstab	nanorc	sysctl.conf gai.conf	network	sysctl.d groff	networks systemd group	newt	terminfo group-	nsswitch.conf	timezone grub.d	opt	tmpfiles.d gshadow	os-release	ucf.conf gshadow-	pam.conf	udev gss	pam.d	ufw hdparm.conf	passwd	update-motd.d host.conf	passwd-	vim hostname	perl	wgetrc hosts	profile	X11 hosts.allow	profile.d	xdg hosts.deny protocols	xml root@debian:~#`

As Gema suggested, I tried to save the page, when opening vim, it looks like:
```<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"></head><body>tcgetattr: Inappropriate ioctl for device
[SOL Session operational.  Use ~? for help]

root@debian:~# ls /etc/
adduser.conf            init             python
adjtime                 init.d           python2.7
alternatives            initramfs-tools  python3
apm                     inputrc          python3.5
apparmor                iproute2         rc0.d
apparmor.d              issue            rc1.d
apt                     issue.net        rc2.d
bash.bashrc             kernel           rc3.d
bash_completion         kernel-img.conf  rc4.d
bash_completion.d       ldap             rc5.d
bindresvport.blacklist  ld.so.cache      rc6.d
binfmt.d                ld.so.conf       rcS.d
ca-certificates         ld.so.conf.d     reportbug.conf
ca-certificates.conf    libaudit.conf    resolv.conf
calendar                locale.alias     rmt 
console-setup           locale.gen       rpc
cron.d                  localtime        rsyslog.conf
cron.daily              logcheck         rsyslog.d
cron.hourly             login.defs       securetty
cron.monthly            logrotate.conf   security
crontab                 logrotate.d      selinux
cron.weekly             machine-id       services
dbus-1                  magic            sgml
debconf.conf            magic.mime       shadow
debian_version          mailcap          shadow-
default                 mailcap.order    shells
deluser.conf            manpath.config   skel
dhcp                    mime.types       ssh
dictionaries-common     mke2fs.conf      ssl 
discover.conf.d         modprobe.d       staff-group-for-usr-local
discover-modprobe.conf  modules          subgid
dpkg                    modules-load.d   subgid-
emacs                   motd             subuid
environment             mtab             subuid-
fstab                   nanorc           sysctl.conf
gai.conf                network          sysctl.d
groff                   networks         systemd
group                   newt             terminfo
group-                  nsswitch.conf    timezone
grub.d                  opt              tmpfiles.d
gshadow                 os-release       ucf.conf
gshadow-                pam.conf         udev
gss                     pam.d            ufw
hdparm.conf             passwd           update-motd.d
host.conf               passwd-          vim
hostname                perl             wgetrc
hosts                   profile          X11
hosts.allow             profile.d        xdg
hosts.deny              protocols        xml
root@debian:~# </body></html>```

**Comment by gemagomez** [comment]
This is unavoidable, the browser does that when showing the page. Saving the page is the easiest solution to this issue.
