### ISSUE TITLE
BMC should be just another interface

### ISSUE THREAD

**Issue by rengolin** [Linaro/mr-provisioner#87]
With the BMCs associated with machines, they show up in the list. But
I still have to create a BMC (copy and paste mac, ip) and associate it
with the machine. If the DHCP changes the IP (can happen during
migrations, config change), you'll have to change the IPs of *all*
BMCs by hand, even though MrP already does that to the interfaces
themselves in the machine list.

The idea is to have another type of interface, a BMC, which has two
additional fields (user/pass) and that' it. So, whenever you add it to
the machine (from Discovery), you can say that's a BMC + user/pass,
and you're done. Everything else is up to the DHCP server

**Comment by gemagomez** [comment]
Whenever BMC DHCP support is implemented, it'd be the same way it is done for machines - by having an interface associated with a BMC (much like what is done for machines). BMCs remain primary objects.

BMC DHCP will be addressed by issue #77

**Comment by bwalex** [comment]
It makes way more sense to keep BMCs as primary entities. You are glancing over at least these other concerns:

 - bmc info (i.e. cartridge number or similar), so it's more than just user/pass
 - similar to the above, if you start adding support for more BMC types, the situation would just get worse; some "BMC" types might require additional configuration beyond user/pass
 - It would screw over features such as #7
