### ISSUE TITLE
Add machine status for machines that have requested DHCP

### ISSUE THREAD

**Issue by rengolin** [Linaro/mr-provisioner#88]
Right now we have a machines status for when the machine is up, provided by IPMI. We also need a statu for when it has requested an IP via DHCP.

This is important to allow access for other tools to know when the machine has finished booting. This would help Jenkins jobs knowing when the installation finished, the new system has booted and requested an
IP. Either a hook mechanism (a URL to hit when the event is seen, for example), or allow polling would do.

**Comment by gemagomez** [comment]
For automation you are supposed to use the API, which has a "state" property on machines. This state is not fully implemented yet (see issue #22), but is supposed to track a machine from the beginning of being rebooted/started for provisioning all the way to a phone-home event notifying it that the machine is ready.
