### ISSUE TITLE
multiarch support

### ISSUE THREAD

**Issue by gemagomez** [Linaro/mr-provisioner#9]
All file types and machines should have an architecture and sub-architecture property defining the architecture they support. Architectures would be things like aarch64, x86_64. Sub-architectures could then be x86_64-efi vs x86_64-bios.

This also enables some UI improvements to filter files based on the machine's architecture.

**Comment by hrw** [comment]
kernels, initrd files are arch specific

preseed files can be all/aarch64/x86-64 due to arch specific options/packages

**Comment by hrw** [comment]
when it comes to subarchs... I hope that we can just standardize on uefi ;D

**Comment by gemagomez** [comment]
Closed as part of #63.
