### ISSUE TITLE
Single option chosen on drop down menus when required

### ISSUE THREAD

**Issue by rengolin** [Linaro/mr-provisioner#90]
Things like image architecture, boot sub-architecture that now can
have multiple choices. Initially, they have only one, so they should
have the only one choice selected on drop-down menus instead of
complaining they have to be selected.

Note: This is **IF** there's only one option _and_ **IF** it's mandatory, select the only option automatically.

**Comment by gemagomez** [comment]
Making a default choice on those is a bad idea in my opinion. The case may be that this machine is a new architecture and the admin needs to add it, making this choice by default for them makes the workflow less obvious.
